apiVersion: v1
kind: ServiceAccount
metadata:
  name: myservice-account
  namespace: default

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: default
  name: myservice-role
rules:
- apiGroups: [""]
  resources: ["pods", "services", "endpoints", "persistentvolumeclaims"]
  verbs: ["get", "list", "watch", "create", "delete"]
- apiGroups: ["apps"]
  resources: ["deployments", "replicasets"]
  verbs: ["get", "list", "watch", "create", "delete"]

---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: myservice-rolebinding
  namespace: default
subjects:
- kind: ServiceAccount
  name: myservice-account
  namespace: default
roleRef:
  kind: Role
  name: myservice-role
  apiGroup: rbac.authorization.k8s.io
